[build-system]
requires = ["setuptools~=80.0.0", "wheel~=0.45.0"]
build-backend = "setuptools.build_meta"

[project]
name = "money-manager"
version = "0.1.0"
description = "Money manager application"
readme = "README.md"
requires-python = ">=3.13"
keywords = ["money", "expense", "budget", "finance"]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: End Users/Desktop"
]
dependencies = [
    "python-dotenv==1.2.1",
]

[project.optional-dependencies]
dev = ["pytest~=9.0.0"]

[project.scripts]
money-manager = "money_manager.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
